### PR TITLE
(maint) lib should only be used for ruby code

### PR DESCRIPTION
**Pull request by adreyer**
lib is synced with pluginsync and is automatically added to the ruby
loadpath. Modules should therefore only put ruby code in lib and use
files for task helpers in other languages.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Want to add release prep? Version number bump and changelog.

**Comment by MikaelSmith** [comment]
This also needs corresponding Bolt docs changes.

**Comment by MikaelSmith** [comment]
There's an argument that we shouldn't put the ruby task helper in lib either, because Puppet will still pluginsync it.

**Comment by adreyer** [comment]
At least ruby code wont' break require. 

I think it's a reasonable argument though. Use lib for type and provider code and use files for everything else.

**Review by lucywyman — APPROVED** [review]

**Pull request merged**
